sudo: required
dist: trusty

language: cpp
compiler:
  - g++

cache:
  apt: true
  directories:
    - $HOME/.cache

env:
  global:
    - BOOST_BUILD_PATH: $HOME/.cache/boost_build
    - BOOST_ROOT: $HOME/.cache/boost_1_61_0

before_install:
  # download boost
  - cd $HOME/.cache
  - wget https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.gz
  - tar xfz boost_1_61_0.tar.gz
  - cd -

  # install Boost.Build
  - cd $BOOST_ROOT/tools/build
  - ./bootstrap.sh
  - ./b2 install --prefix=$BOOST_BUILD_PATH --cxxflaags="-std=c++11"
  - export PATH=$PATH:$BOOST_BUILD_PATH/bin
  - cd -

install:
  - b2 giecs

script:
  - b2 test

